#ifndef State_h
#define State_h

enum State {
	SCREEN_MAIN,
	SCREEN_MENU_TIME,
	SCREEN_MENU_UP_TIME,
	SCREEN_MENU_DOWN_TIME,
	SCREEN_MENU_UP_POSITION,
	SCREEN_MENU_DOWN_POSITION,
	SCREEN_DO_DOWN_POSITION,
	SCREEN_DO_TIME_HOUR,
	SCREEN_DO_TIME_MINUTE
};
State currentState = SCREEN_MAIN;

#endif
